apply plugin: 'com.android.application'

android {
    namespace 'net.iowaline.dotdash'
    compileSdk 35

    defaultConfig {
        applicationId "io.github.dotdashmodern.keyboard"
        minSdk 23
        targetSdk 35
        versionCode 20
        versionName "2.0.1-mvp"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
